export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const SEARCH_PRODUCTS_START = 'SEARCH_PRODUCTS_START';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const GET_SEARCHED_PRODUCTS = 'GET_SEARCHED_PRODUCTS';

export const GET_PRODUCT_START = 'GET_PRODUCT_START';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';

export const GET_SEARCHED_PRODUCT = 'GET_SEARCHED_PRODUCT';
export const ADD_PRODUCT_TO_LIST = 'ADD_PRODUCT_TO_LIST';
export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';
export const UPLOAD_PRODUCT_LIST = 'UPLOAD_PRODUCT_LIST';
export const REMOVE_PRODUCT_FROM_LIST = 'REMOVE_PRODUCT_FROM_LIST';
export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
